
name: CI

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/sanman1k98/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
